name = "senti-bot-worker"
main = "index.js"

# Твій акаунт
account_id = "2cf6e316af8623546c95c0354bc3aa00"

# Сумісність з новим Wrangler v4
compatibility_date = "2025-09-19"
compatibility_flags = ["nodejs_compat"]

# Публікуємо на workers.dev
workers_dev = true